name: medispro
version: 1.0.5+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.67.0
  pie_chart: ^5.3.2
  flutter_staggered_animations: ^1.1.1
  dio: ^5.4.3+1
  get_storage: ^2.1.1
  home_widget: ^0.5.0
  shimmer_animation: ^2.1.0
  pull_to_refresh: ^2.0.0
  package_info: ^2.0.2
  in_app_update: ^4.2.1
  device_info_plus: ^10.1.0
  search_page: ^2.3.0
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
